FROM golang:alpine AS builder
WORKDIR /app
COPY . .
RUN go build -ldflags="-w -s" -o edgegpt-http main.go

FROM alpine
WORKDIR /app
COPY --from=builder /app/edgegpt-http .

EXPOSE 8080
CMD ["/app/edgegpt-http"]